[package]
name = "dem_viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
show-image = "0.13"
colorgrad = "0.6"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
walkdir = "2.4"
